StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6070A09F7C9276AA}" {
   Id "Abrams-EditableEntity_M1A1_Name"
   Target_en_us "M1A1"
   Comment "Enity placed via the content Browser"
   MaxLength 0
   Modified 1699222138
   Author "Ethan Benzel"
   LastChanged "mikia"
  }
  CustomStringTableItem "{659D55111B39E473}" {
   Id "Abrams-EditableEntity_M1A1_TUSK_Name"
   Target_en_us "M1A1 - TUSK"
   Modified 1704810293
   Author "thoma"
   LastChanged "thoma"
  }
  CustomStringTableItem "{6070A09F284710CE}" {
   Id "Abrams-EditableEntity_M1A2_Name"
   Target_en_us "M1A2"
   Modified 1699222134
   Author "Ethan Benzel"
   LastChanged "mikia"
  }
  CustomStringTableItem "{6070A09F2DAED935}" {
   Id "Abrams-EditableEntity_M1A2_TUSK_Name"
   Target_en_us "M1A2 - TUSK"
   Modified 1699222154
   Author "Ethan Benzel"
   LastChanged "mikia"
  }
  CustomStringTableItem "{6070A09F32160A41}" {
   Id "Abrams-EditableEntity_M1A2_TUSKII_Name"
   Target_en_us "M1A2 - TUSK II"
   Modified 1699222149
   Author "Ethan Benzel"
   LastChanged "mikia"
  }
  CustomStringTableItem "{65481B28EDA900EF}" {
   Id "Abrams-EditableEntity_M1A2SEP_Name"
   Target_en_us "M1A2SEP"
   Modified 1699225043
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{65481B28EFFC228E}" {
   Id "Abrams-EditableEntity_M1A2SEP_TUSK_Name"
   Target_en_us "M1A2SEP - TUSK"
   Modified 1699225059
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{65481B28E1C3FD72}" {
   Id "Abrams-EditableEntity_M1A2SEP_TUSKII_Name"
   Target_en_us "M1A2SEP - TUSK II"
   Modified 1699225052
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{65480D66BDF70B49}" {
   Id "Abrams-EditableEntity_M1A2SEPV2_Name"
   Target_en_us "M1A2SEPV2"
   Modified 1699222105
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{65480D66B0234458}" {
   Id "Abrams-EditableEntity_M1A2SEPV2_TUSK_Name"
   Target_en_us "M1A2SEPV2 - TUSK"
   Modified 1699222162
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{65480D66B56743EF}" {
   Id "Abrams-EditableEntity_M1A2SEPV2_TUSKII_Name"
   Target_en_us "M1A2SEPV2 - TUSK II"
   Modified 1699222118
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{64852B6AFACFC32E}" {
   Id "SPC-Magazine_M256_APFSDS_A2_Description"
   Target_en_us "Ammunition rack loaded with M829A2 armor piercing fin stabilized discarding sabot rounds."
   Modified 1686455394
   Author "thoma"
   LastChanged "thoma"
  }
  CustomStringTableItem "{647C15EF9E5E211E}" {
   Id "SPC-Magazine_M256_APFSDS_Description"
   Target_en_us "Ammunition rack loaded with M829 armor piercing fin stabilized discarding sabot rounds."
   Modified 1686455296
   Author "thoma"
   LastChanged "thoma"
  }
  CustomStringTableItem "{647C15EFADBC3E30}" {
   Id "SPC-Magazine_M256_APFSDS_Name"
   Target_en_us "120×44mm 20rnd M256 APFSDS Rack"
   Modified 1685857005
   Author "thoma"
   LastChanged "thoma"
  }
  CustomStringTableItem "{647C15EF9619BE51}" {
   Id "SPC-Magazine_M256_HEATFS_Description"
   Target_en_us "Ammunition rack loaded with M830 high-explosive anti-tank fin stabilized rounds."
   Modified 1685857181
   Author "thoma"
   LastChanged "thoma"
  }
  CustomStringTableItem "{647C15EFA8200F73}" {
   Id "SPC-Magazine_M256_HEATFS_Name"
   Target_en_us "120×44mm 20rnd M256 HEATFS Rack"
   Modified 1685857197
   Author "thoma"
   LastChanged "thoma"
  }
 }
}